name: Build Dependencies
on:
  workflow_call:
    inputs:
      multi-platform-build:
        type: boolean
        default: true

jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: ${{ (inputs.multi-platform-build && matrix.os) || 'ubuntu-latest' }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
    steps:
      - uses: actions/checkout@v3

      - name: Cache Rust Bindings
        id: cache-rust-bindings
        uses: actions/cache@v3
        with:
          path: |
            rust-bindings/target/release/*csharp_bindings.*
            rust-bindings/csharp-bindings/bindings/Libsql.g.cs
          key: ${{ runner.os }}-rust-bindings-${{ hashFiles('./generate-bindings.sh') }}
          restore-keys: |
            ${{ runner.os }}-rust-bindings-

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: 'true'

      - name: Generate bindings
        if: |
          steps.cache-rust-bindings.outputs.cache-hit != 'true'
        run: devbox run -- just generate-bindings --remote https://github.com/tvandinther/libsql --commit add-missing-statement-functions
        shell: bash

      - name: Upload bindings
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.os }}
          path: |
            rust-bindings/target/release/*csharp_bindings.*
            rust-bindings/csharp-bindings/bindings/Libsql.g.cs
          if-no-files-found: error
